export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  BIODATAS: "/biodatas",
  BIODATA_DETAILS: (id: string) => `/biodatas/${id}`,
  CHECKOUT: (id: string) => `/checkout/${id}`,
  CONTACT: "/contact",
  ABOUT: "/about",
  MY_PROFILE: "/dashboard/my-profile",
  DASHBOARD_USER: "/dashboard/user-home",
  DASHBOARD_ADMIN: "/dashboard/admin-home",
  MANAGE_BIODATA: "/dashboard/manage-biodata",
  MY_CONTACT_REQUESTS: "/dashboard/my-contact-requests",
  MY_FAVOURITES: "/dashboard/my-favourites",
  GOT_MARRIED: "/dashboard/got-married",
  USERS: "/dashboard/users",
  APPROVE_PREMIUM: "/dashboard/approve-premium",
  APPROVE_CONTACT: "/dashboard/approve-contact-requests",
  SUCCESS_STORIES: "/dashboard/admin/success-stories",
} as const;
